@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant "v:ViewAllLoansCommand" as ViewAllLoansCommand LOGIC_COLOR
participant "r:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("viewallloans")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("viewallloans")
activate AddressBookParser

create ViewAllLoansCommand
AddressBookParser -> ViewAllLoansCommand
activate ViewAllLoansCommand
ViewAllLoansCommand --> AddressBookParser
deactivate ViewAllLoansCommand

AddressBookParser --> LogicManager : v
deactivate AddressBookParser

LogicManager -> ViewAllLoansCommand : execute(m)
activate ViewAllLoansCommand

ViewAllLoansCommand -> Model : setLoanList(...)
activate Model
Model --> ViewAllLoansCommand

create CommandResult
ViewAllLoansCommand -> CommandResult
activate CommandResult
CommandResult --> ViewAllLoansCommand
deactivate CommandResult

ViewAllLoansCommand --> LogicManager : r
deactivate ViewAllLoansCommand




[<--LogicManager
deactivate LogicManager
@enduml
